version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/deploy/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh  #최상위 디렉토리의 script 폴더 내의 shell script가 실행된다.
      timeout: 60
      runas: ec2-user