spring:
  datasource:
    url: jdbc:mysql://localhost:3306/withspace?serverTimezone=Asia/Seoul
    username: root
    password: dong6348@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true